version: '3.3'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonar
    ports:
      - 9000:9000
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
      - ./sonarqube_temp:/opt/sonarqube/temp